### ISSUE TITLE
Copy + Paste (Clipboard)

### ISSUE THREAD

**Issue by lagden** [woliveiras/vimparanoobs#3]
Só não fui pro `VIM` por causa do disso!!! hehehe...
Na verdade a pergunta é: Você já abandou o Sublime ou Atom?

**Comment by woliveiras** [comment]
Eu quase desisti de aprender por isso também! AUHAUHAUHA

Ainda não estou usando 100% o VIM cara.

Eu não tive tempo pra pegar o VIM e dar uma boa brincada, até aprender e poder usar, de fato, no dia-a-dia.

No trabalho eu já tenho produtividade com o Sublime, então não posso abandonar e perder essa produtividade atééé pegar o esquema do VIM (se não é rua, né? kkkk).

Então uso o VIM em casa enquanto estou estudando ou editando algo menos complicado.

Até removi todos os plugins que estava usando pra aprender mesmo e só depois ir acrescentando configurações.

**Comment by lagden** [comment]
Bacana...
Acho que vc deveria se empenhar...
http://csswizardry.com/2014/06/vim-for-people-who-think-things-like-vim-are-weird-and-hard/

O que vou estava pensando para fazer a migração é montar um lista das features que mais uso no sublime, por exemplo:

- split
- split diff
- selecionar várias linhas
- indentação de código
- copy paste (area de transferência)
- find and replace
- find and replace em todos os arquivos do projeto com a ext .js
- editorconfig
- lint para js
- etc...

E anotar no papel os comandos e ir pras cabeças!!
Acho que assim vai...

A sua idéia de deixar plugin less é uma boa, na verdade o meu sublime tem poucos!!

**Comment by woliveiras** [comment]
Putz, meu Sublime é abarrotado de plugins cara! kkk

Então, eu fiz essa lista de comandos também.

Comandos e Plugins, ai iria migrar assim que descobrisse como usar cada comando e plugins parecidos pro VIM, mas acabou que fiquei sem tempo (comecei a Faculdade) ai estragou a brincadeira.

Fiquei empolgado, agora, pra voltar a tentar! kkkk

Vou dar uma atenção melhor pro VIM nos finais de semana. \o/

Depois vai render [mais um post](https://woliveiras.com.br/posts/Comecando-com-o-editor-de-texto-VIM/) sobre isso!
